[package]
name = "GraficasProyecto1Raycasting"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra-glm = "0.10"
minifb = "0.27.0"
nalgebra = "0.33.0"
rand = "0.8.5"
image = "0.25.2"
once_cell = "1.19.0"
rusttype = "0.9.3"
rodio = "0.19.0"

